# BruceOS — Calamares Bootloader Module

efiBootLoader: "grub"

kernel:      "/vmlinuz-linux"
img:         "/initramfs-linux.img"
fallback:    "/initramfs-linux-fallback.img"

kernelLine:  ", with BruceOS"
fallbackKernelLine: ", with BruceOS (fallback)"

grubInstall: "grub2-install"
grubMkconfig: "grub2-mkconfig"
grubCfg:     "/boot/grub2/grub.cfg"
grubProbe:   "grub2-probe"

efiBootMgr:  "efibootmgr"

installEFIFallback: true
