# BruceOS — Calamares Partition Module

efiSystemPartition:     "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: EFI

userSwapChoices:
    - none
    - small
    - file

# Default filesystem
defaultFileSystemType: "ext4"

# Available filesystems
availableFileSystemTypes: ["ext4", "btrfs", "xfs"]

# Enable encryption option
enableLuksAutomatedPartitioning: true

# Allow manual partitioning
drawNestedPartitions:   false
alwaysShowPartitionLabels: true

initialPartitioningChoice: erase
initialSwapChoice: file

defaultPartitionTableType: gpt
