# BruceOS — Calamares Unpackfs Module
# Unpacks the live filesystem image to the target

unpack:
    -   source: "/run/initramfs/live/LiveOS/squashfs.img"
        sourcefs: "squashfs"
        destination: ""
