# BruceOS — Calamares Users Module

defaultGroups:
    - name: users
      must_exist: true
      system: true
    - name: wheel
      must_exist: false
      system: true
    - name: video
      must_exist: false
      system: true
    - name: audio
      must_exist: false
      system: true
    - name: network
      must_exist: false
      system: true

autologinGroup: autologin

doAutologin: false

sudoersGroup: wheel

setRootPassword: false

doReusePassword: true

passwordRequirements:
    minLength: 1
    maxLength: -1
    nonempty: true

allowWeakPasswords: true
allowWeakPasswordsDefault: false

userShell: /usr/bin/fish

setHostname: EtcFile
writeHostsFile: true
