# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0
#
# BruceOS Calamares Settings
# Fedora 43 based, GNOME desktop, ext4 default

modules-search: [ local, /usr/lib64/calamares/modules ]

branding: bruceos

prompt-install: false

dont-chroot: false

oem-setup: false

disable-cancel: false
disable-cancel-during-exec: false

quit-at-end: true

sequence:
    - show:
        - welcome
        - locale
        - keyboard
        - partition
        - users
        - summary
    - exec:
        - partition
        - mount
        - unpackfs
        - machineid
        - fstab
        - locale
        - keyboard
        - localecfg
        - networkcfg
        - hwclock
        - services-systemd
        - dracut
        - initramfscfg
        - users
        - displaymanager
        - bootloader
        - shellprocess@post-install
        - umount
    - show:
        - finished
